"""enforce_currency_and_provider_not_null

Revision ID: 8df16ea1f99c
Revises: 74e5d762e896
Create Date: 2025-12-19 01:10:13.808894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df16ea1f99c'
down_revision: Union[str, None] = '74e5d762e896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'currency')
    op.drop_column('payments', 'provider')
    op.drop_column('product_media', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
